name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
    - name: Build Manager Tests
      working-directory: ./build
      run: cmake --build . --target VDSProject_test -j 4
    - name: Run Manager Tests
      run: ./build/src/test/VDSProject_test
    - name: Build Reachability Tests
      working-directory: ./build
      run: cmake --build . --target VDSProject_reachability -j 4
    - name: Run Reachability Tests
      run: ./build/src/reachability/VDSProject_reachability
