name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create and Change to Build Directory
      run: mkdir build && cd build
    - name: Configure CMake
      run: cmake ..
    - name: Build
      run: cmake --build . --target VDSProject_test -j 4
    - name: Run
      run: ./VDSProject_test
